/* Generated by myoptions.h generator - v0.9.0 */
/* https://trip5.github.io/ehRadio_myoptions/generator.html */
/* https://github.com/e2002/yoradio */

/* esp32-S3-devkit-C1 44 pins https://randomnerdtutorials.com/esp32-s3-devkitc-pinout-guide */

/* HSPI (SPI 2) GPIO 11 - MOSI, GPIO 12 - CLK, GPIO 13 - MISO, GPIO 10 - CS */

#ifndef myoptions_h
#define myoptions_h

#define L10N_LANGUAGE EN // HU NL PL RU EN EL Enter your own language here!!
#define NAMEDAYS_FILE HU // HU, PL, NL
#define CLOCK_TTS_LANGUAGE "en" //Default language TTS e.g. pl,en,de,ru,fr,hu
//#define USDATE   //US Date format
//#define IMPERIALUNIT

// --- DLNA / Synology ---
//#define USE_DLNA
//#define dlnaHost "192.168.180.122" // DLNA server IP address
//#define dlnaIDX  21  //MUSIC container index, on Synology NAS is usually 21

/******************************************/
// --- Special GPIOs on ProS3 ---
#define LDO2_ENABLE   17 // LDO2 (3V3_AUX) - HIGH to enable
#define RF_SWITCH     11 // Switches between internal and external Antenna - HIGH to use external 
/******************************************/

/******************************************/
// --- Max MAX17048 LiPo fuel guage on ProS3 ---
#define BATTERY_SDA   8
#define BATTERY_SCL   9
#define BATTERY_INT   10
/******************************************/

/******************************************/
// --- ProS3 USB/charge sense ---
#define CHARGE_SENSE_PIN 33   // ProS3 GPIO33 = 5V sense (via divider)
/******************************************/

/******************************************/
#define LED_BUILTIN_S3    18     /* S3-onboard RGB led pin */
#define USE_BUILTIN_LED true /* The RGB LED does not turn on.. */
/*****************************************/
//#define DSP_MODEL DSP_ILI9486
//#define DSP_MODEL DSP_ILI9488
#define DSP_MODEL DSP_ILI9341
//#define DSP_MODEL DSP_ST7735
//#define DSP_MODEL DSP_ST7789_76
//#define DSP_MODEL DSP_ST7789_170
//#define DSP_MODEL DSP_1602I2C    //2x16 
//#define DSP_MODEL DSP_2004I2C   //4x20
//#define DSP_MODEL DSP_ST7789
//#define DSP_MODEL DSP_SH1106
//#define SH1106_GRAYSCALE  true
//#define DSP_MODEL DSP_SSD1306
//#define DSP_MODEL DSP_GC9A01A
//#define HUN_LCD
/*****************************************/

#define DSP_HSPI 1

#define TFT_DC 5
#define TFT_CS 4
#define TFT_RST 2
#define TFT_SCK   36
#define TFT_MOSI  35
#define TFT_MISO  37

#define BRIGHTNESS_PIN 14
/*****************************************/
// #define NEXTION_RX      15
// #define NEXTION_TX     16
/*****************************************/
/* Touch panel*/

//#define TS_MODEL TS_MODEL_XPT2046
//#define TS_CS 42
/*****************************************/
/* SD CARD */
//#define SDC_CS    39
/****************************************/
/*  I2S DAC  */

/* PCM5102A  DAC */
#define I2S_DOUT 40
#define I2S_BCLK 41
#define I2S_LRC  42

/* ENCODER 1 */
#define ENC_BTNR 13 // S2
#define ENC_BTNL 15 // S1
#define ENC_BTNB 16 // KEY
#define ENC_INTERNALPULLUP		true

/* ENCODER 2 */
//#define ENC2_BTNR 0 // S2
//#define ENC2_BTNL 21 // S1
//#define ENC2_BTNB 3 // KEY
//#define ENC2_INTERNALPULLUP		true
/********************************************/

/* ÓRA MODUL RTC DS3132 */
// #define RTC_SCL     9
// #define RTC_SDA     8
// #define RTC_MODULE DS3231
/********************************************/

/* REMOTE CONTROL INFRARED RECEIVER */
//#define IR_PIN 12

/********************************************/
#define VUMETER true
#define CLOCK_12H true
/********************************************/
/*  Egyéb beállítások.  */
//#define MUTE_PIN     2            /*  MUTE Pin */
//#define MUTE_VAL    LOW          /*  Write this to MUTE_PIN when player is stop */
//#define PLAYER_FORCE_MONO false  /*  mono option on boot - false stereo, true mono. "false" */
#define I2S_INTERNAL    false    /*  If true - use esp32 internal DAC. "false" */
//#define ROTATE_90   false        /*  Optional 90 degree rotation for square displays."false"*/
#define TFT_ROTATE      2        /*  Display rotation. 0 - 0, 1 - 90, 2 - 180, 3 - 270 degrees */
//#define HIDE_VOLPAGE             /* Hangerő elrejtés, navigálj a hangerő folyamatjelző sávjával.*/
//#define WAKE_PIN      1
//#define LIGHT_SENSOR      40               /*  Light sensor  */
//#define AUTOBACKLIGHT(x)  *function*        /*  Autobacklight function. See options.h for example  */
//#define NAME_STRIM              /* Az állomás nevének megjelenítése a streamből. (MOD Maleksm)*/

//#define DOWN_LEVEL           2      /* lowest level brightness (from 0 to 255) */
//#define DOWN_INTERVAL        60     /* interval for BacklightDown in sec (60 sec = 1 min) */
/* ***************************************** */

#endif
