/* Generated by myoptions.h generator - v0.9.0 */
/* https://trip5.github.io/ehRadio_myoptions/generator.html */
/* https://github.com/e2002/yoradio */

/* esp32-S3-devkit-C1 44 pins https://randomnerdtutorials.com/esp32-s3-devkitc-pinout-guide */

/* HSPI (SPI 2) GPIO 11 - MOSI, GPIO 12 - CLK, GPIO 13 - MISO, GPIO 10 - CS */

#ifndef myoptions_h
#define myoptions_h

#define L10N_LANGUAGE EN // HU NL PL RU EN EL Enter your own language here!!
//#define NAMEDAYS_FILE HU // Optional name-day calendar (HU, PL, CZ, GR, NL, UA, DE)
#define CLOCK_TTS_LANGUAGE "en" //Default language TTS e.g. pl,en,de,ru,fr,hu
//#define USDATE   //US Date format
//#define IMPERIALUNIT

// --- DLNA / Synology ---
//#define USE_DLNA
//#define dlnaHost "192.168.180.122" // DLNA server IP address
//#define dlnaIDX  21  //MUSIC container index, on Synology NAS is usually 21

/******************************************/
// --- Special GPIOs on ProS3 ---
#define LDO2_ENABLE   17 // LDO2 (3V3_AUX) - HIGH to enable
#define RF_SWITCH     11 // Switches between internal and external Antenna - HIGH to use external
#define CHARGE_SENSE_PIN 33   // ProS3 GPIO33 = 5V sense

// PROS3 option: use external antenna at boot (via RF_SWITCH).
// Set to 0 if you want to use the internal antenna.
#define PROS3_USE_EXTERNAL_ANTENNA 1
/******************************************/

/******************************************/
// --- Max MAX17048 LiPo fuel guage on ProS3 ---
#define BATTERY_ENABLED 1  // Set to 0 to disable ALL battery gauge/UI logic (useful if no battery is connected)
#define BATTERY_SDA   8
#define BATTERY_SCL   9
#define BATTERY_INT   10

// Footer battery icon: colorize by % (comment out to use theme color)
#define FOOTER_BATTERY_COLORIZE 1
/******************************************/

/******************************************/
#define LED_BUILTIN_S3    255     /* S3-onboard LED pin */
#define USE_BUILTIN_LED false /* The LED doesn't turn on.. */

// ProS3 has an onboard NeoPixel (WS2812) on GPIO18.
// We'll initialize it in `src/yoradio_user.cpp` and set it to black at boot to
// prevent it latching random colors from boot-time pin noise.
#define BUILTIN_NEOPIXEL_PIN 18
// Brightness used only while clearing the onboard NeoPixel at boot.
#define BUILTIN_NEOPIXEL_BOOT_BRIGHTNESS 50

// NeoStatus (NeoPixel ring/status LED)
//
// Keep `myoptions.h` minimal:
// - Hardware pins/count
// - Colors
// - Global brightness cap
//
// All timing/steps/pulse tuning is set as defaults in `neostatus.cpp`.
#define NEOSTATUS_ENABLE 1

// Hardware: NeoPixel ring behind rotary knob (8px) on GPIO14.
// (Replaces the ProS3 onboard 1px NeoPixel.)
#define NEOSTATUS_PIN 14
#define NEOSTATUS_COUNT 8

// Global NeoPixel brightness cap (0..255). Applies to ring/pixel animations.
#define NEOSTATUS_BRIGHTNESS 255

// Enable toggles (only keep the effects we want)
#define NEOSTATUS_BOOT_ANIM_ENABLE 1
#define NEOSTATUS_POD_INDEX_ANIM_ENABLE 1

// Core playback/idle animations
#define NEOSTATUS_PLAY_ANIM_ENABLE 1        // start -> playing -> stop -> idle continuity
#define NEOSTATUS_IDLE_GLOW_ENABLE 1

// Event animations
#define NEOSTATUS_SLEEP_ANIM_ENABLE 1
#define NEOSTATUS_WIFI_ANIM_ENABLE 1
#define NEOSTATUS_LOW_BATT_ANIM_ENABLE 1
#define NEOSTATUS_BT_ANIM_ENABLE 1

// CSS color names (as "r, g, b" macros).
// Ref: https://www.cssportal.com/css-color-names/
#define CSS_BLACK 0, 0, 0
#define CSS_WHITE 255, 255, 255
#define CSS_RED 255, 0, 0
#define CSS_BLUE 0, 0, 255
#define CSS_GREEN 0, 128, 0
#define CSS_LIME 0, 255, 0
#define CSS_TEAL 0, 128, 128
#define CSS_AQUA 0, 255, 255
#define CSS_FUCHSIA 255, 0, 255
#define CSS_YELLOW 255, 255, 0
#define CSS_ORANGE 255, 165, 0
#define CSS_GOLD 255, 215, 0
#define CSS_PURPLE 128, 0, 128
#define CSS_DEEPPINK 255, 20, 147
#define CSS_DEEPSKYBLUE 0, 191, 255
#define CSS_REBECCAPURPLE 102, 51, 153
#define CSS_CYAN 0, 255, 255

// Volume / follow-screen tuning moved to `neostatus.cpp` defaults.

// Event colors (use CSS_* names above)
// Keep only the colors for the effects we are retaining.
#define NEOSTATUS_BOOT_RGB CSS_GREEN
#define NEOSTATUS_VOL_RGB CSS_GREEN
// Podcast indexing color.
#define NEOSTATUS_POD_INDEX_RGB CSS_DEEPPINK

// Idle glow color (lowest brightness "status present" cue).
#define NEOSTATUS_IDLE_GLOW_RGB CSS_GREEN

// Sleep cue (purple pulses, never fully off between pulses).
#define NEOSTATUS_SLEEP_RGB_A CSS_REBECCAPURPLE
#define NEOSTATUS_SLEEP_RGB_B CSS_DEEPPINK

// Wi-Fi events
#define NEOSTATUS_WIFI_CONN_RGB CSS_LIME
#define NEOSTATUS_WIFI_LOST_RGB CSS_ORANGE

// Low battery alert (red/orange)
#define NEOSTATUS_LOW_BATT_RGB_A CSS_RED
#define NEOSTATUS_LOW_BATT_RGB_B CSS_ORANGE

// Bluetooth events
#define NEOSTATUS_BT_CONN_RGB CSS_DEEPSKYBLUE
#define NEOSTATUS_BT_AUDIO_RGB CSS_BLUE

// Playback palettes (start/playing/stop share these per mode)
#define NEOSTATUS_WEB_RGB_A CSS_WHITE
#define NEOSTATUS_WEB_RGB_B CSS_DEEPSKYBLUE
#define NEOSTATUS_SD_RGB_A CSS_GOLD
#define NEOSTATUS_SD_RGB_B CSS_ORANGE
#define NEOSTATUS_POD_RGB_A CSS_DEEPPINK
#define NEOSTATUS_POD_RGB_B CSS_REBECCAPURPLE

// Mode/Power button LED hardware + toggles
#define MODE_BUTTON_LED_PIN 34
#define MODE_BUTTON_LED_ACTIVE_HIGH 1
#define MODE_BUTTON_LED_IDLE_BREATHE_ENABLE 0
#define MODE_BUTTON_LED_PRESS_PULSE_ENABLE 1

// Optional cap for the ledstrip plugin (separate from LEDSTRIP_BRIGHTNESS).
// Uncomment if you ever enable `USE_LEDSTRIP_PLUGIN`.
//#define LEDSTRIP_MAX_BRIGHTNESS_PCT 5
//#define USE_LEDSTRIP_PLUGIN
//#define LEDSTRIP_PIN    48      // GPIO pin connected to LED data line
//#define LEDSTRIP_COUNT  144     // total number of LEDs (must be even)

/*****************************************/
//#define DSP_MODEL DSP_ILI9486
//#define DSP_MODEL DSP_ILI9488
#define DSP_MODEL DSP_ILI9341
//#define DSP_MODEL DSP_ST7735
//#define DSP_MODEL DSP_ST7789_76
//#define DSP_MODEL DSP_ST7789_170
//#define DSP_MODEL DSP_1602I2C    //2x16 
//#define DSP_MODEL DSP_2004I2C   //4x20
//#define DSP_MODEL DSP_ST7789
//#define DSP_MODEL DSP_SH1106
//#define SH1106_GRAYSCALE  true
//#define DSP_MODEL DSP_SSD1306
//#define DSP_MODEL DSP_GC9A01A
//#define HUN_LCD
/*****************************************/
#define TFT_SPI_FREQ 60000000UL
//#define DSP_HSPI 1
#define TFT_DC 5
#define TFT_CS 4
#define TFT_RST 2
//#define TFT_SCK   36
//#define TFT_MOSI  35
//#define TFT_MISO  37

// TFT backlight brightness pin
#define BRIGHTNESS_PIN 7
/*****************************************/

// Optional UI toggles
// Uncomment to hide individual widgets globally:
// #define HIDE_CLOCK
// #define HIDE_DATE_WIDGET

// Track position overlay ("mm:ss / mm:ss") for SD + Podcast playback.
// Note: On some layouts this overlaps the weather text area.
// - Set TRACKPOS_REPLACE_WEATHER_WHILE_PLAYING=1 to temporarily hide weather while playing.
#define TRACKPOS_ENABLE 1
#define TRACKPOS_REPLACE_WEATHER_WHILE_PLAYING 0

/*****************************************/
// #define NEXTION_RX      15
// #define NEXTION_TX     16
/*****************************************/
/* Touch panel*/

//#define TS_MODEL TS_MODEL_XPT2046
//#define TS_CS 42
/*****************************************/

/*****************************************/
/* ENCODER 1 */
#define ENC_BTNR 15 // S2
#define ENC_BTNL 16 // S1
#define ENC_BTNB 13 // KEY
#define ENC_INTERNALPULLUP		true

/* ENCODER 2 */
//#define ENC2_BTNR 0 // S2
//#define ENC2_BTNL 21 // S1
//#define ENC2_BTNB 3 // KEY
//#define ENC2_INTERNALPULLUP		true

/* Buttons */
#define BTN_INTERNALPULLUP    true
#define BTN_MODE     12
/********************************************/

/******************************************/
// --- New hardware (PCB rev) ---
// NeoStatus + Mode button LED options are grouped near the top of this file.
/******************************************/

/********************************************/
/*  I2S DAC  */

/* PCM5102A  DAC */
#define I2S_DOUT 40
#define I2S_BCLK 41
#define I2S_LRC  42

// --- Optional: Bi-amp (2x MAX98357) DSP crossover ---
// Wiring approach (no extra I2S peripheral needed):
// - Both MAX98357 share the same I2S signals: BCLK/LRC/DIN.
// - Strap one amp to "Left" and the other to "Right" via its LRC strap pin.
// Then yoRadio can output low frequencies on one channel and highs on the other.
//
// Safety defaults:
// - Disabled by default (set BIAMP_ENABLE=1 to turn on).
// - Automatically bypassed while Bluetooth output is selected.

#define BIAMP_ENABLE 1
#define BIAMP_TEST_MODE 0

#ifndef BIAMP_ENABLE
  #define BIAMP_ENABLE 0
#endif
#ifndef BIAMP_DISABLE_WHEN_BT
  #define BIAMP_DISABLE_WHEN_BT 1
#endif
// Crossover frequency (Hz). Typical 3" woofer + tweeter: 2000-4000 Hz.
#ifndef BIAMP_CROSSOVER_HZ
  #define BIAMP_CROSSOVER_HZ 2500
#endif
// Channel mapping: 1 => low=L, high=R. 0 => low=R, high=L.
#ifndef BIAMP_LOW_ON_LEFT
  #define BIAMP_LOW_ON_LEFT 1
#endif

// Debugging aid: make bi-amp behavior obvious.
// 0 = normal crossover.
// 1 = swap low/high outputs L<->R periodically (bass/treble "bounces" between amps).
#ifndef BIAMP_TEST_MODE
  #define BIAMP_TEST_MODE 0
#endif
// Swap period (ms) when BIAMP_TEST_MODE=1.
#ifndef BIAMP_TEST_TOGGLE_MS
  #define BIAMP_TEST_TOGGLE_MS 500
#endif

// Low-rate serial diagnostics for bi-amp DSP (prints only on state changes).
// 1 = enable logs like:
//   [BIAMP] fs=44100Hz fc=2500Hz map=low->L btBypass=1
#ifndef BIAMP_DIAG_LOG
  #define BIAMP_DIAG_LOG 1
#endif

// Mute
#define MUTE_PIN     39            /*  MUTE Pin */
#define MUTE_VAL    LOW          /*  Write this to MUTE_PIN when player is stop */
/********************************************/

/********************************************/
/* Companion ESP32 for Bluetooth A2DP TX */
// ProS3 (ESP32-S3) is BLE-only, so A2DP requires a second (Classic BT) ESP32.
// UART:
//   ProS3 TX GPIO43 -> HiGrow RX GPIO39 (series resistor ~1k)
//   ProS3 RX GPIO44 <- HiGrow TX GPIO13 (series resistor ~1k)
// Wake:
//   ProS3 GPIO38 -> HiGrow GPIO38 (EXT0 wake on HiGrow)
#define BT_COMPANION_ENABLE 1
#define BT_COMPANION_UART_PORT 1
#define BT_COMPANION_UART_BAUD 115200
#define BT_COMPANION_UART_TX   43
#define BT_COMPANION_UART_RX   44
#define BT_COMPANION_WAKE_PIN  38
#define BT_COMPANION_WAKE_PULSE_MS 600
#define BT_COMPANION_SINK_NAME "HiFi-IIS"
/********************************************/

/*****************************************/
/* RTC module (DS3231) */

// #define RTC_SCL     9
// #define RTC_SDA     8
// #define RTC_MODULE DS3231
/********************************************/

/*****************************************/
/* REMOTE CONTROL INFRARED RECEIVER */

#define IR_PIN 21
/*****************************************/

/*****************************************/
/* SD CARD */

#define SDC_CS    1
// SD card SPI clock (Hz). You can run TFT much faster than SD even on the same bus.
// Start conservative for stability; increase only if verified stable.
#define SDSPISPEED 10000000

// Experimental: SD album art (cover.jpg/folder.jpg) decode + render.
// Keep this enabled only while testing; disable if you see SD playback instability.
#define SD_ALBUM_ART_ENABLE 0
/*****************************************/

/********************************************/
/* Other settings */

// SD resume: when switching into SD mode, auto-play the last SD track.
// Set to 0 to disable.
#define SD_AUTORESUME_ON_MODE_SWITCH 1

// Station logos + album art (runtime toggle default).
// Set to 0 if you want them hidden by default after flashing.
#define SHOW_LOGOS_DEFAULT 1

//#define PLAYER_FORCE_MONO false  /*  mono option on boot - false stereo, true mono. "false" */
#define I2S_INTERNAL    false    /*  If true - use esp32 internal DAC. "false" */
//#define ROTATE_90   false        /*  Optional 90 degree rotation for square displays."false"*/
//#define TFT_ROTATE      2        /*  Display rotation. 0 - 0, 1 - 90, 2 - 180, 3 - 270 degrees */
//#define HIDE_VOLPAGE             /* Hide volume page; navigate using the volume progress bar. */

/* DEEP SLEEP OPTIONS */
// Deep sleep wake button (RTC GPIO only: GPIO0..GPIO21).
// If you already have a MODE/encoder button wired, you can point WAKE_PIN1 at that GPIO.
// Example:
//   #define WAKE_PIN1  1
// Optional: second wake pin (e.g. IR wake)
//   #define WAKE_PIN2  <gpio>
#define WAKE_PIN1 BTN_MODE
#define WAKE_PIN2 ENC_BTNB
#define WAKE_PIN3 IR_PIN
// --- Auto deep sleep (power-off) rules ---
// 1) If battery is critically low and not on 5V, deep sleep immediately.
// 2) If nothing has been playing for a while, deep sleep (wake via WAKE_PIN1/2).
//
// If WAKE_PIN1/2 are not configured, we avoid auto-sleep to prevent "bricking"
// the device in deep sleep with no wake source.
#define AUTO_DEEPSLEEP_IDLE_MINUTES 15
#define AUTO_DEEPSLEEP_BATT_PCT 5

/* BACKLIGHT OPTIONS */
#define FADE_PERIOD 300
// Ambient light auto-dimming (BH1750 over I2C on the same pins as MAX17048: GPIO8/9).
// Enable the backlight plugin with `BRIGHTNESS_PIN` (already set for this build),
// then optionally enable the BH1750 integration here.
//
// Wiring:
// - BH1750 VCC -> 3V3
// - BH1750 GND -> GND
// - BH1750 SDA -> GPIO8  (BATTERY_SDA)
// - BH1750 SCL -> GPIO9  (BATTERY_SCL)
// - BH1750 ADDR: leave low for 0x23 (default) or strap high for 0x5C
#define BH1750_ENABLE 1
#define BH1750_I2C_ADDR 0x23
#define BH1750_UPDATE_MS 1000
// Map lux -> brightness% (and smooth).
#define BH1750_LUX_MIN 1.0f
#define BH1750_LUX_MAX 50.0f
//#define BH1750_BRIGHTNESS_MIN_PCT 5
//#define BH1750_BRIGHTNESS_MAX_PCT 100
//#define BH1750_SMOOTH_ALPHA_X100 25
//#define BH1750_GAMMA 0.60f
//#define BH1750_RESPECT_USER_MAX 1
// Optional diagnostics: print lux + target/applied brightness (rate-limited).
#define BH1750_DIAG_LOG 1
//
// Notes:
// - The user brightness slider remains your "cap"; auto brightness won't exceed it.
// - Auto brightness drives PWM directly (no EEPROM writes).
//#define DOWN_LEVEL           2      /* lowest level brightness (from 0 to 255) */
//#define DOWN_INTERVAL        60     /* interval for BacklightDown in sec (60 sec = 1 min) */

/* MQTT options */
// - Set MQTT_DISABLE=1 to fully disable MQTT features (including HA discovery).
// - Set MQTT_QUIET_LOGS=1 to suppress noisy AsyncMqttClient INFO logs on Serial.
#ifndef MQTT_DISABLE
  #define MQTT_DISABLE 0
#endif
#ifndef MQTT_QUIET_LOGS
  #define MQTT_QUIET_LOGS 1
#endif

/* ***************************************** */

/* ***************************************** */
/* DIAGNOSTICS */

/* Display diagnostics */
//#define DSP_DIAG_LOG 1
//#define VU_PERF_LOG 1

/* Audio diagnostics */
//#define AUDIO_DIAG_LOG 1
// optional
//#define AUDIO_DIAG_LOG_INTERVAL_MS 1000

//#define AUDIO_TASK_CORE_ID 0
//#define DSP_TASK_CORE_ID 1

// ---- Controls task (optional, DISABLED by default) ----
// Default behavior (recommended for audio stability) is to poll controls on every
// Arduino `loop()` via `loopControls()` (the original behavior).
//
// To enable the extra controls polling task
// #define CONTROLS_TASK_ENABLE 1
//
// To force-disable (even if enabled elsewhere):
//#define CONTROLS_TASK_DISABLE 1

// Keep controls polling off the audio core so it can't steal time from AAC decode.
// Display is already on core 0 (DspTask), and button polling is very light.
//#define CONTROLS_TASK_CORE_ID 0

// Lower than the Arduino loop task; audio stability comes first.
//#define CONTROLS_TASK_PRIORITY 1

// Lower tick rate reduces any chance of interfering with display timing.
//#define CONTROLS_TASK_PERIOD_MS 10

/* ***************************************** */

#endif
