[env:yoradio-esp32s3n16r8-ili9431]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
board = um_pros3
framework = arduino

extra_scripts =
    pre:tools/pio/apply_audio_idf_mod.py

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
    -O2 

build_unflags = -std=gnu++17

board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.psram = qspi

board_build.partitions = partitions/partition_16MB_ota_spiffs.csv
board_build.filesystem = spiffs

lib_deps =
    adafruit/Adafruit GFX Library@^1.12.3
    adafruit/Adafruit ILI9341@^1.6.2
    adafruit/Adafruit MAX1704X

upload_speed = 921600
upload_protocol = esptool
upload_flags =
    --chip=esp32s3
    --before=default_reset
    --after=hard_reset
    --baud=921600

monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
