/* Generated by myoptions.h generator - v0.9.0 */
/* https://trip5.github.io/ehRadio_myoptions/generator.html */
/* https://github.com/e2002/yoradio */

/* esp32-S3-devkit-C1 44 pins https://randomnerdtutorials.com/esp32-s3-devkitc-pinout-guide */

/* HSPI (SPI 2) GPIO 11 - MOSI, GPIO 12 - CLK, GPIO 13 - MISO, GPIO 10 - CS */

#ifndef myoptions_h
#define myoptions_h

#define L10N_LANGUAGE EN // HU NL PL RU EN EL Enter your own language here!!
#define NAMEDAYS_FILE HU // HU, PL, NL
#define CLOCK_TTS_LANGUAGE "en" //Default language TTS e.g. pl,en,de,ru,fr,hu
//#define USDATE   //US Date format
//#define IMPERIALUNIT

// --- DLNA / Synology ---
//#define USE_DLNA
//#define dlnaHost "192.168.180.122" // DLNA server IP address
//#define dlnaIDX  21  //MUSIC container index, on Synology NAS is usually 21

/******************************************/
// --- Special GPIOs on ProS3 ---
#define LDO2_ENABLE   17 // LDO2 (3V3_AUX) - HIGH to enable
#define RF_SWITCH     11 // Switches between internal and external Antenna - HIGH to use external
#define CHARGE_SENSE_PIN 33   // ProS3 GPIO33 = 5V sense

// PROS3 option: force external antenna at boot (via RF_SWITCH).
// Set to 0 if you want to use the internal antenna.
#define PROS3_FORCE_EXTERNAL_ANTENNA 1
/******************************************/

/******************************************/
// --- Max MAX17048 LiPo fuel guage on ProS3 ---
#define BATTERY_SDA   8
#define BATTERY_SCL   9
#define BATTERY_INT   10

// Footer battery icon: colorize by % (comment out to use theme color)
#define FOOTER_BATTERY_COLORIZE 1
/******************************************/

/******************************************/
#define LED_BUILTIN_S3    255     /* S3-onboard LED pin */
#define USE_BUILTIN_LED false /* The LED doesn't turn on.. */

// ProS3 has an onboard NeoPixel (WS2812) on GPIO18.
// We'll initialize it in `src/yoradio_user.cpp` and set it to black at boot to
// prevent it latching random colors from boot-time pin noise.
#define BUILTIN_NEOPIXEL_PIN 18

// Optional cap for the ledstrip plugin (separate from LEDSTRIP_BRIGHTNESS).
// Uncomment if you ever enable `USE_LEDSTRIP_PLUGIN`.
//#define LEDSTRIP_MAX_BRIGHTNESS_PCT 5
//#define USE_LEDSTRIP_PLUGIN
//#define LEDSTRIP_PIN    48      // GPIO pin connected to LED data line
//#define LEDSTRIP_COUNT  144     // total number of LEDs (must be even)
/*****************************************/
//#define DSP_MODEL DSP_ILI9486
//#define DSP_MODEL DSP_ILI9488
#define DSP_MODEL DSP_ILI9341
//#define DSP_MODEL DSP_ST7735
//#define DSP_MODEL DSP_ST7789_76
//#define DSP_MODEL DSP_ST7789_170
//#define DSP_MODEL DSP_1602I2C    //2x16 
//#define DSP_MODEL DSP_2004I2C   //4x20
//#define DSP_MODEL DSP_ST7789
//#define DSP_MODEL DSP_SH1106
//#define SH1106_GRAYSCALE  true
//#define DSP_MODEL DSP_SSD1306
//#define DSP_MODEL DSP_GC9A01A
//#define HUN_LCD
/*****************************************/

//#define DSP_HSPI 1

#define TFT_DC 5
#define TFT_CS 4
#define TFT_RST 2
//#define TFT_SCK   36
//#define TFT_MOSI  35
//#define TFT_MISO  37

#define BRIGHTNESS_PIN 14
/*****************************************/
// #define NEXTION_RX      15
// #define NEXTION_TX     16
/*****************************************/
/* Touch panel*/

//#define TS_MODEL TS_MODEL_XPT2046
//#define TS_CS 42
/*****************************************/
/* SD CARD */
#define SDC_CS    1

// SD resume: when switching into SD mode, auto-play the last SD track.
// Set to 0 to disable.
#define SD_AUTORESUME_ON_MODE_SWITCH 1
/****************************************/
/*  I2S DAC  */

/* PCM5102A  DAC */
#define I2S_DOUT 40
#define I2S_BCLK 41
#define I2S_LRC  42

/* ENCODER 1 */
#define ENC_BTNR 13 // S2
#define ENC_BTNL 15 // S1
#define ENC_BTNB 16 // KEY
#define ENC_INTERNALPULLUP		true

/* ENCODER 2 */
//#define ENC2_BTNR 0 // S2
//#define ENC2_BTNL 21 // S1
//#define ENC2_BTNB 3 // KEY
//#define ENC2_INTERNALPULLUP		true
/********************************************/

/* RTC module (DS3231) */
// #define RTC_SCL     9
// #define RTC_SDA     8
// #define RTC_MODULE DS3231
/********************************************/

/* REMOTE CONTROL INFRARED RECEIVER */
#define IR_PIN 21

/********************************************/

/********************************************/
/* Other settings */
#define BTN_MODE     12
#define MUTE_PIN     39            /*  MUTE Pin */
#define MUTE_VAL    LOW          /*  Write this to MUTE_PIN when player is stop */
//#define PLAYER_FORCE_MONO false  /*  mono option on boot - false stereo, true mono. "false" */
#define I2S_INTERNAL    false    /*  If true - use esp32 internal DAC. "false" */
//#define ROTATE_90   false        /*  Optional 90 degree rotation for square displays."false"*/
//#define TFT_ROTATE      2        /*  Display rotation. 0 - 0, 1 - 90, 2 - 180, 3 - 270 degrees */
//#define HIDE_VOLPAGE             /* Hide volume page; navigate using the volume progress bar. */
// Deep sleep wake button (RTC GPIO only: GPIO0..GPIO21).
// If you already have a MODE/encoder button wired, you can point WAKE_PIN1 at that GPIO.
// Example:
//   #define WAKE_PIN1  1
// Optional: second wake pin (e.g. IR wake)
//   #define WAKE_PIN2  <gpio>
#define WAKE_PIN1 BTN_MODE
#define WAKE_PIN2 ENC_BTNB
// --- Auto deep sleep (power-off) rules ---
// 1) If battery is critically low and not on 5V, deep sleep immediately.
// 2) If nothing has been playing for a while, deep sleep (wake via WAKE_PIN1/2).
//
// If WAKE_PIN1/2 are not configured, we avoid auto-sleep to prevent "bricking"
// the device in deep sleep with no wake source.
#define AUTO_DEEPSLEEP_IDLE_MINUTES 15
#define AUTO_DEEPSLEEP_BATT_PCT 5
#define FADE_PERIOD 300
//#define LIGHT_SENSOR      40               /*  Light sensor  */
//#define AUTOBACKLIGHT(x)  *function*        /*  Autobacklight function. See options.h for example  */
//#define NAME_STRIM              /* Show station name from the stream. (MOD Maleksm) */

// MQTT options
// - Set MQTT_DISABLE=1 to fully disable MQTT features (including HA discovery).
// - Set MQTT_QUIET_LOGS=1 to suppress noisy AsyncMqttClient INFO logs on Serial.
#ifndef MQTT_DISABLE
  #define MQTT_DISABLE 0
#endif
#ifndef MQTT_QUIET_LOGS
  #define MQTT_QUIET_LOGS 1
#endif

//#define DOWN_LEVEL           2      /* lowest level brightness (from 0 to 255) */
//#define DOWN_INTERVAL        60     /* interval for BacklightDown in sec (60 sec = 1 min) */
/* ***************************************** */

#endif
